# The URL the site will be built for
base_url = "https://letfunny.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
bottom_footnotes = true

[markdown.highlighting]
theme = "github-light"
extra_grammars = ["syntaxes/tlaplus.json"]

[slugify]
paths_keep_dates = true

[extra]
# Put all your custom variables here
